twig:
    charset: 'UTF-8'
    form_themes: ['bootstrap_4_layout.html.twig']
    file_name_pattern: '*.twig'
    globals:
        charset: 'UTF-8'
    strict_variables: '%kernel.debug%'  # Active strict_variables seulement en dev/test
       