<?php

namespace ContainerB9xLxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X6y1FeXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x6y1FeX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x6y1FeX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cart' => ['privates', 'App\\Class\\Cart', 'getCartService', false],
        ], [
            'cart' => 'App\\Class\\Cart',
        ]);
    }
}
