<?php

namespace ContainerB9xLxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressControllerFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X31fmBZ.App\Controller\Account\AddressController::Form()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X31fmBZ.App\\Controller\\Account\\AddressController::Form()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'addressRepository' => ['privates', 'App\\Repository\\AddressRepository', 'getAddressRepositoryService', true],
            'cart' => ['privates', 'App\\Class\\Cart', 'getCartService', false],
        ], [
            'addressRepository' => 'App\\Repository\\AddressRepository',
            'cart' => 'App\\Class\\Cart',
        ]))->withContext('App\\Controller\\Account\\AddressController::Form()', $container);
    }
}
