<?php

namespace ContainerB9xLxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.It8UU_Q.App\Controller\Account\AddressController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.It8UU_Q.App\\Controller\\Account\\AddressController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'addressRepository' => ['privates', 'App\\Repository\\AddressRepository', 'getAddressRepositoryService', true],
        ], [
            'addressRepository' => 'App\\Repository\\AddressRepository',
        ]))->withContext('App\\Controller\\Account\\AddressController::delete()', $container);
    }
}
