<?php

namespace ContainerB9xLxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x5hc6oM.App\Controller\CartController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x5hc6oM.App\\Controller\\CartController::delete()'] = ($container->privates['.service_locator.x5hc6oM'] ?? $container->load('get_ServiceLocator_X5hc6oMService'))->withContext('App\\Controller\\CartController::delete()', $container);
    }
}
