# config/services.yaml
parameters:
    mailer_from: '%env(MAILER_FROM)%'
    mailtrap_host: '%env(MAILTRAP_HOST)%'
    mailtrap_port: '%env(MAILTRAP_PORT)%'
    mailtrap_username: '%env(MAILTRAP_USERNAME)%'
    mailtrap_password: '%env(MAILTRAP_PASSWORD)%'
    mailtrap_from_name: '%env(MAILTRAP_FROM_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\PhpMailerService:
        arguments:
            $params: '@parameter_bag'
        tags:
            - { name: 'monolog.logger', channel: 'mailer' }


    Src\EventSubscriber\LoginSubscriber:
        tags: [kernel.event_subscriber]
    App\EventSubscriber\TwigGlobalSubscriber:
        tags: ['kernel.event_subscriber']