<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB9xLxbP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB9xLxbP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB9xLxbP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB9xLxbP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB9xLxbP\App_KernelDevDebugContainer([
    'container.build_hash' => 'B9xLxbP',
    'container.build_id' => '16242148',
    'container.build_time' => 1752059730,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB9xLxbP');
